name: Build and Release Windows App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Type check and build
        run: npm run build:win

      - name: Show build outputs (debug)
        run: ls -R dist
